<<<<<<< HEAD
version: 2 # use CircleCI 2.0 #
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point

  docker: # run the steps with Docker
  — image: circleci/openjdk:8-jdk-stretch # …with this image as the primary container; this is where all `steps` will run

  steps: # a collection of executable commands
  — checkout # Checkout the code from Github
  — run: ./mvnw clean install # mvn clean install tells Maven to do the clean phase in each module before running the install phase for each module.
=======
version: 2
jobs:
    build:
        docker:
            # specify the version you desire here
            - image: circleci/openjdk:11-browsers-legacy

            # Specify service dependencies here if necessary
            # CircleCI maintains a library of pre-built images
            # documented at https://circleci.com/docs/2.0/circleci-images/
            # - image: circleci/postgres:9.4

        working_directory: ~/repo

        environment:
            # Customize the JVM maximum heap limit
            MAVEN_OPTS: -Xmx3200m

        steps:
            - checkout

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "pom.xml" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run: mvn dependency:go-offline

            - save_cache:
                  paths:
                      - ~/.m2
                  key: v1-dependencies-{{ checksum "pom.xml" }}

            # run tests!
            - run: mvn integration-test
>>>>>>> d5325a6f4ce6a0dcf8404113e420df550e7a051c
